import type { Metadata } from "next";
// import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper"; // If session management is required
import { Toaster } from "sonner"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   weight: ["400", "500", "600", "700", "800"], 
// });

export const metadata: Metadata = {
  title: "Links Hub",
  description: "Generated by create next app",
};
// ${geistSans.variable} ${poppins.variable}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <>
          <SessionWrapper>
            {children}
            <Toaster richColors/>
          </SessionWrapper>
        </>
      </body>
    </html>
  );
}
